name: Build Infrastructure

on:
    workflow_dispatch: 

jobs:
  build-terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_load_balancer_arn_customer: ${{ vars.LOAD_BALANCER_ARN_CUSTOMER }}
      TF_VAR_load_balancer_dns_customer: ${{ vars.LOAD_BALANCER_DNS_CUSTOMER }}
      TF_VAR_load_balancer_arn_orders: ${{ vars.LOAD_BALANCER_ARN_ORDERS }}
      TF_VAR_load_balancer_dns_orders: ${{ vars.LOAD_BALANCER_DNS_ORDERS }}
      TF_VAR_load_balancer_arn_payment: ${{ vars.LOAD_BALANCER_ARN_PAYMENT }}
      TF_VAR_load_balancer_dns_payment: ${{ vars.LOAD_BALANCER_DNS_PAYMENT }}
      TF_VAR_fastfood_aws_access_key_id: ${{ secrets.FASTFOOD_AWS_ACCESS_KEY_ID }}
      TF_VAR_fastfood_aws_secret_access_key: ${{ secrets.FASTFOOD_AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.FASTFOOD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.FASTFOOD_AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.FASTFOOD_AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Terraform Init
        run: |
            cd infra
            terraform init

      - name: Terraform Plan
        run: |
            cd infra
            terraform plan

      - name: Terraform Apply
        run: |
            cd infra
            terraform apply --auto-approve